services:
    nginx:
        container_name: sail-nginx
        image: 'nginx:stable'
        ports:
            - '${HTTP_PORT:-8888}:80'
            - '${SSL_PORT:-443}:443'
        environment:
            - SSL_PORT=${SSL_PORT:-443}
            - APP_SERVICE=${APP_SERVICE:-laravel.test}
            - SERVER_NAME=${SERVER_NAME:-localhost}
            - TZ= Asia/Tokyo
        volumes:
            - 'sail-nginx:/etc/nginx/certs'
            - './nginx/templates:/etc/nginx/templates'
            - './vendor/ryoluo/sail-ssl/nginx/generate-ssl-cert.sh:/docker-entrypoint.d/99-generate-ssl-cert.sh'
        depends_on:
            - ${APP_SERVICE:-laravel.test}
        networks:
            - sail
    # ngrok:
    #     image: 'ngrok/ngrok:alpine'
    #     environment:
    #         NGROK_AUTHTOKEN: '${NGROK_AUTHTOKEN}'
    #     command: 'http laravel.test:80'
    #     ports:
    #         - '4040:4040'
    #     networks:
    #         - sail
    #     depends_on:
    #         - laravel.test

    laravel.test:

        container_name: sail-8.2
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
                WWWUSER: 1000
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-88}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWGROUP: 1000
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            POST_MAX_SIZE: 2000M
            UPLOAD_MAX_FILESIZE: 2000M
            PHP_MEMORY_LIMIT: 2000M
            UPLOAD_LIMIT: 2000M
            TZ: Asia/Tokyo
        volumes:
            - '.:/var/www/html'
            # - './repository/ht/data:/home/xs314565/repository/ht/data'
            # - './repository/ht/master:/home/xs314565/repository/ht/master'
            # - './repository/web/data:/home/xs314565/repository/web/data'
            # - './repository/web/master:/home/xs314565/repository/web/master'
        networks:
            - sail
        # depends_on:
            # - mysql
            # - redis
            # - meilisearch
            # - mailpit
            # - selenium

# DBサーバー

    # mysql:
    #     image: 'mariadb:10.5.22'
    #     ports:
    #         - '${FORWARD_DB_PORT:-3306}:3306'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_ROOT_HOST: '%'
    #         MYSQL_DATABASE: '${DB_DATABASE}'
    #         MYSQL_USER: '${DB_USERNAME}'
    #         MYSQL_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #         TZ: Asia/Tokyo
    #     volumes:
    #         - 'sail-mysql:/var/lib/mysql'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - mysqladmin
    #             - ping
    #             - '-p${DB_PASSWORD}'
    #         retries: 3
    #         timeout: 5s
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     depends_on:
    #         - mysql
    #     environment:
    #         - PMA_ARBITRARY=1
    #         - 'PMA_HOSTS=${DB_HOST}'
    #         - 'PMA_USER=${DB_USERNAME}'
    #         - 'PMA_DATABASE=${DB_DATABASE}'
    #         - 'PMA_PASSWORD=${DB_PASSWORD}'
    #         - 'POST_MAX_SIZE=2000M'
    #         - 'UPLOAD_MAX_FILESIZE=2000M'
    #         - 'PHP_MEMORY_LIMIT=2000M'
    #         - 'UPLOAD_LIMIT=2000M'
    #         - TZ= Asia/Tokyo
    #     ports:
    #         - '3000:80'
    #     networks:
    #         - sail


    # redis:
    #     image: 'redis:alpine'
    #     ports:
    #         - '${FORWARD_REDIS_PORT:-6379}:6379'
    #     volumes:
    #         - 'sail-redis:/data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - redis-cli
    #             - ping
    #         retries: 3
    #         timeout: 5s
    # meilisearch:
    #     image: 'getmeili/meilisearch:latest'
    #     ports:
    #         - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
    #     volumes:
    #         - 'sail-meilisearch:/meili_data'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test:
    #             - CMD
    #             - wget
    #             - '--no-verbose'
    #             - '--spider'
    #             - 'http://localhost:7700/health'
    #         retries: 3
    #         timeout: 5s
    # mailpit:
    #     image: 'axllent/mailpit:latest'
    #     ports:
    #         - '${FORWARD_MAILPIT_PORT:-1025}:1025'
    #         - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    #     environment:
    #         - TZ= Asia/Tokyo
    #     networks:
    #         - sail
    # selenium:
    #     image: selenium/standalone-chrome
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     volumes:
    #         - '/dev/shm:/dev/shm'
    #     environment:
    #         - TZ= Asia/Tokyo
    #     networks:
    #         - sail

# FTPサーバー

    # ftpd_server:
    #     container_name: ftpd_server
    #     image: stilliard/pure-ftpd
    #     ports:
    #         - '21:21'
    #         - '30000-30009:30000-30009'
    #     networks:
    #         - sail
    #     volumes:
    #         - './repository/ht/data:/repository/ht/data'
    #         - './repository/web/data:/repository/web/data'
    #         - './repository/web/master:/repository/web/master'
    #         - './ftp/passwd:/etc/pure-ftpd/passwd'
    #     environment:
    #         PUBLICHOST: localhost
    #         FTP_USER_NAME: testuser
    #         FTP_USER_PASS: test123
    #         FTP_USER_HOME: /repository/web/master
    #         TZ: Asia/Tokyo
    #     restart: always
networks:
    sail:
        driver: bridge
volumes:
    sail-laravel.test:
        driver: local
    sail-nginx:
        driver: local
    # sail-mysql:
    #     driver: local
    sail-redis:
        driver: local
    sail-meilisearch:
        driver: local
